# Generated by Django 6.1.1 on 2026-10-03 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meter_number', models.CharField(max_length=30, unique=True)),
                ('pin', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('watts', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hours_per_day', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='tracker.household')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_bought', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tracker.household')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
